### ISSUE TITLE
No requirements.txt

### ISSUE THREAD

**Issue by TrentWeiss** [TUMFTM/MixNet#1]
Hi Guys,

Thanks for open-sourcing this. Super cool stuff! 

I noticed both the README and the Dockerfile both specify a stage to install Python dependencies via pip with a requirements.txt file.   At time of writing, no such file is actually tracked by git in this repo.  I noticed the .gitignore excludes *.txt (a sensible choice), perhaps the requirements file was mistakenly never committed due to being excluded from a "git add"?

Adding my own requirements.txt file to make the Dockerfile work was trivial, but I just filled it in with my best guess for what python stuff would be needed (torch, numpy, matplotlib, etc... the standard dependencies most ML stuff needs). Any chance you could force add (git add -f) the actual requirements.txt file you guys use and push it?

Thanks,
Trent

**Comment by phkarle** [comment]
Hi Trent,

Thanks for the hint. I just added the requirements.txt, which we used during development and testing.

Best regards,
Phillip
